baseurl      = "svjampana.github.io"
title        = "Saketh Jampana"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disable404     = false

[author]
  name = "Saketh Jampana"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Security Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Saketh's Personal Website"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/svjampana"

  [[params.social]]
    name = "email"
    url  = "mailto:svjampana@yahoo.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/svjampana"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jsakethvarma"

[taxonomies]
    category = "category"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Saketh Jampana"
    subtitle = ""
    keywords = ""
    copyright = ''

    [languages.en.params.logo]
      logoText = "cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
